### ISSUE TITLE
1.3 Find all attributes retrievable by FAV gentor

### ISSUE THREAD

**Issue by radomirbosak** [radomirbosak/unfun-html#20]
```yaml
name: Kragen
urlname: Kragen
title: Kragen, der
article: der
part_of_speech: Substantiv, maskulin
usage: null
frequency: 2
word_separation:
- Kra
- gen
meaning_overview:
- - den Hals teilweise oder ganz umschließender Teil der Kleidung
  - einzelner, nicht fest an ein Kleidungsstück genähter Kragen (1a)
- - (meist von Geflügel) Hals
  - Hals einer Flasche
- gegen das übrige Fell oder Gefieder abstechender Streifen um den, am Hals von Tieren
- ''
origin: mittelhochdeutsch krage = Hals, Kehle, Nacken; Kragen (1), ursprünglich =
  Schlund
compounds: null
grammar_raw: []
synonyms:
- Gurgel, Kehle
words_before:
- Kraftwerksbetreiberin
- Kraftwort
- Kragdach
- Krage
- Krägelchen
words_after:
- Kragenbär
- Kragenecke
- Kragenknopf
- kragenlos
- Kragennummer
```
